[package]
name = "egui-sdl2-event"
authors = ["Valtteri Vallius"]
version = "0.1.0"
edition = "2021"
keywords = ["sdl2", "egui"]
categories = ["gui", "input"]
license = "MIT"
readme = "README.md"


[dependencies]
sdl2 = "0.35.2"
egui = { version = "0.18.1" }
